### PR TITLE
fix: use frontmatterPosition end line

### LINKED ISSUE #647: [FEATURE REQUEST] Appending to existing file while considering the frontmatter
**Is your feature request related to a problem? Please describe.**
For now, If I use QuickAdd to append a existing note which frontmatter with this option:
image

It would just insert the text BEFORE the original frontmatter.. which would break the frontmatter function.

**Describe the solution you'd like**
So I was wondering could there be a new option "Append to the top (Ignore frontmatter)"
And with this, put the content before the CONENT but AFTER the frontmatter ?
Thus not breaking thr original frontmatter.

### PR DESCRIPTION
**Pull request by edongashi**

### CODE REVIEW

**Comment by chhoumann** [comment]
Hey @edongashi, thank you for taking the time to contribute!

It looks like the API may have changed since this was originally merged, IIRC. Glad you wrote a fix!

Your PR doesn't resolve #647 because that regards Templates, whereas this modifies code for Captures. So I removed the `fix` from your PR body to prevent that issue from closing when I merge this.

**Review by chhoumann — APPROVED** [review]

**Comment by edongashi** [comment]
Thank you @chhoumann!
 
> It looks like the API may have changed since this was originally merged, IIRC. Glad you wrote a fix!

The API change was acknowledged in the previous PR #595, but I think by accident the wrong line was deleted [here](https://github.com/chhoumann/quickadd/pull/595#discussion_r1439247067)

> Your PR doesn't resolve https://github.com/chhoumann/quickadd/issues/647 because that regards Templates, whereas this modifies code for Captures.

Thanks for being vigilant, I tried to do some housekeeping given the large number of issues. I gave the issue a second look, and I don't see how this related to templates. Can you please double check?

**Comment by chhoumann** [comment]
Of course. The contents of the issue sounds more relevant to a Capture, but specifically mentions a setting that is only available in Templates:
image

I checked & can recreate the issue they presented with the setting.
You would have to set the file name to be the same as the file name of an existing file. Then it would try to create the note, notice there's already a file, and instead proceed by simply adding the text to the top of the note, disregarding the frontmatter.

**Comment by edongashi** [comment]
Understood, thanks and keep up the good work!

**Comment by chhoumann** [comment]
Thank you, likewise!

**Pull request merged**
