### PR TITLE
Make Api public

### LINKED ISSUE #138: [FEATURE REQUEST] Make API public
### Discussed in https://github.com/chhoumann/quickadd/discussions/135

<div type='discussions-op-text'>

<sup>Originally posted by **ramon86** November  3, 2021</sup>
I hope this is something that's easy to achieve, but I cannot figure out how to use QuickAddAPI in other javascript contexts (in my case within a dataviewjs block).

The examples all work with it being available from the params object that's passed when you use actual QuickAdd macros, but is it possible to reference it on other ways as well?</div>

### PR DESCRIPTION
**Pull request by kosei28**
close #138

I made Api public so that it can be used from dataviewjs etc.

### Example
```js
const quickAddApi = this.app.plugins.plugins['quickadd'].api;
const btn = this.container.createEl('button', {text: 'Execute Capture Choice'});
const data = {/* ... */};

btn.addEventListener('click', () => {
  quickAddApi.executeChoice('Capture Choice', {
    X: data.x,
    Y: data.y,
    Z: data.z,
    // ...
  });
});

dv.paragraph(btn);
```

### CODE REVIEW

**Comment by MMoMM-org** [comment]
please take this PR.. I need a way from inside templater scripts to call the api

**Comment by 0Lilian** [comment]
Any news on that ? I also need that functionality, I would really appreciate being able to call the QuickAdd API from Templater scripts

**Comment by kosei28** [comment]
@chhoumann Some people want this PR merged, so please review it.

**Comment by awlobo** [comment]
Can we use the QuickAdd plugin directly from the source if we clone this repo? I would like to test the public API functionality.

**Comment by chhoumann** [comment]
Hi @kosei28, thank you for taking the time to contribute!
And thank you to everyone who has added to the discussion. Your thoughts help me prioritize features and fixes.

While I really appreciate it, I am not currently considering PRs to QA at this moment, as I am trying to rework the plugin to become better and faster.
I have some personal matters which are making this process take longer than expected, so I need to do what I can to make it more manageable.

From the discussion here, I can see that a lot of people really want this feature.
While I wasn't quite yet ready to make this feature yet (re. rework), I think we can make it work.

This implementation isn't quite as desired, and lacks documentation.
So here's what I'll do:
- Make the API public and add @kosei28 as co-author on the commit. Don't want to neglect giving credit.
- Document the newly public API.
- Close this PR and open a new one with the above.
- If the plugin receives an update which breaks the `app.plugins.plugins.quickadd.api` access, it'll be a 'breaking update', and a new 'large' semantic release.

Best,
Christian

**Comment by MMoMM-org** [comment]
an example for the readwise export which is in the metadata part
```
UUID: <% tp.date.now("YYYYMMDDHHmmss") %>
DateStamp: <% tp.date.now("YYYY-MM-DD") %>
Updated: 
publish: false
language: de
Vault: Privat
Year: <% tp.date.now("YYYY") %>
title: "SM - {{title}}" 
<%*
const quickAddApi = this.app.plugins.plugins['quickadd'].api;
quickAddApi.executeChoice('AddReadwise', {X: {{title}}});
-%>
```
this will then add the Note as a link to my Kanban Board for Reading the Readwise articles

**Comment by AB1908** [comment]
I see. That sounds cool. I'm a little unnerved by using code from multiple plugins to get things done as it can be prone to breakage though. Feel free to @ me if you run into issues.

**Pull request closed without merging**
